openapi: 3.0.0
info:
  description: Welcome to Xfers' API documentation. You can find information on our API endpoint specific to your country.
  version: '3'
  title: Xfers Bank Account API
  contact:
    name: Contact us through our help desk
    url: https://bit.ly/XfersSupport
servers:
- description: Indonesia Production
  url: https://id.xfers.com/api
- description: Indonesia Sandbox for testing
  url: https://sandbox-id.xfers.com/api
tags:
- name: Bank Account
  description: API to manage Bank Account
paths:
  /v3/user/bank_account:
    post:
      operationId: addBankAccount
      x-code-samples:
      - lang: Shell
        source: "curl --location --request POST \"$BASE_URL/v3/user/bank_account\" \\\r\n  --header \"X-XFERS-USER-API-KEY: $CUSTOMER_API_KEY\" \\\r\n  --header \"Content-Type: application/json\" \\\r\n  --data \"{\\\"account_no\\\": \\\"1680366060\\\", \\\"bank\\\":\\\"BCA\\\"}\""
      tags:
      - Bank Account
      summary: Add Bank Account
      description: 'This API will be used to attach a new bank account to a user.

        You will be able to withdraw user''s balance to this bank account.

        In Indonesia Production, This API will return the detected_name as provided from the bank.

        The account_holder_name you provided and detected_name needs to be similar (doesn''t need to be 100% match).'
      security:
      - X-XFERS-USER-API-KEY: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              x-custom-requirements:
                Indonesia:
                - account_holder_name
              required:
              - account_no
              - bank
              properties:
                account_no:
                  type: string
                  description: bank account number
                bank:
                  type: string
                  description: Bank abbreviation. You can get the list of bank account abbreviation from the Get Bank and Abbreviation Mapping API.
                account_holder_name:
                  type: string
                  description: Name of bank account holder name. Put 'PROD_ONLY' in Indo Sandbox
            examples:
              Request Body Example:
                summary: Request Body Example
                value:
                  account_no: 0393123432
                  bank: DBS
                  account_holder_name: Tian Wei
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - id: 175
                account_no: '1680366060'
                account_holder_name: PROD ONLY
                detected_name: PROD ONLY
                verification_status: pending
                verified: true
                bank_abbrev: BCA
                usage: all
        4XX:
          $ref: '#/components/responses/v3Error:4XX'
    get:
      operationId: listBankAcc
      x-code-samples:
      - lang: Shell
        source: "curl --location --request GET \"$BASE_URL/v3/user/bank_account\" \\\r\n  --header \"X-XFERS-USER-API-KEY: $CUSTOMER_API_KEY\""
      tags:
      - Bank Account
      summary: List Bank Account
      description: This will list all bank accounts belonging to the user.
      security:
      - X-XFERS-USER-API-KEY: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - id: 175
                account_no: '1680366060'
                account_holder_name: PROD ONLY
                detected_name: PROD ONLY
                verification_status: pending
                verified: true
                bank_abbrev: BCA
                usage: all
        4XX:
          $ref: '#/components/responses/v3Error:4XX'
  /v3/user/bank_account/{bank_account_id}:
    put:
      operationId: updateBankAccount
      x-code-samples:
      - lang: Shell
        source: "curl --location --request PUT \"$BASE_URL/v3/user/bank_account/649\" \\\r\n  --header \"X-XFERS-USER-API-KEY: $CUSTOMER_API_KEY\" \\\r\n  --header \"Content-Type: application/json\" \\\r\n  --data \"{\\\"account_no\\\": \\\"0393123432\\\", \\\"bank\\\":\\\"CIMB_NIAGA\\\", \\\"account_holder_name\\\": \\\"PROD ONLY\\\"}\""
      tags:
      - Bank Account
      summary: Update Bank Account
      description: This request allows you to update an existing bank account record.
      security:
      - X-XFERS-USER-API-KEY: []
      parameters:
      - name: bank_account_id
        in: path
        description: The ID of the bank account. You can retrieve this from in the response of Create Bank Account and List Bank Account API
        required: true
        explode: true
        schema:
          type: string
          example: '175'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              x-custom-requirements:
                Indonesia:
                - account_holder_name
              required:
              - account_no
              - bank
              properties:
                account_no:
                  type: string
                  description: bank account number
                bank:
                  type: string
                  description: Bank abbreviation. You can get the list of bank account abbreviation from the Get Bank and Abbreviation Mapping API.
                account_holder_name:
                  type: string
                  description: Name of bank account holder name. Put 'PROD_ONLY' in Indo Sandbox
            examples:
              Request Body Example:
                summary: Request Body Example
                value:
                  account_no: 0393123432
                  bank: DBS
                  account_holder_name: Tian Wei
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - id: 175
                account_no: '1680366060'
                account_holder_name: PROD ONLY
                detected_name: PROD ONLY
                verification_status: pending
                verified: true
                bank_abbrev: BCA
                usage: all
        4XX:
          $ref: '#/components/responses/v3Error:4XX'
    delete:
      operationId: deleteBankAccount
      x-code-samples:
      - lang: Shell
        source: "curl --location --request DELETE \"$BASE_URL/v3/user/bank_account/175\" \\\r\n  --header \"X-XFERS-USER-API-KEY: $CUSTOMER_API_KEY\" \\\r\n  --data \"\""
      tags:
      - Bank Account
      summary: Delete Bank Account
      description: This request allows you to delete an existing bank account record.
      security:
      - X-XFERS-USER-API-KEY: []
      parameters:
      - name: bank_account_id
        in: path
        description: The ID of the bank account. You can retrieve this from in the response of Create Bank Account and List Bank Account API
        required: true
        explode: true
        schema:
          type: string
          example: '175'
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - id: 175
                account_no: '1680366060'
                account_holder_name: PROD ONLY
                detected_name: PROD ONLY
                verification_status: pending
                verified: true
                bank_abbrev: BCA
                usage: all
        4XX:
          $ref: '#/components/responses/v3Error:4XX'
  /v3/banks:
    get:
      operationId: getBankAbbrev
      x-code-samples:
      - lang: Shell
        source: "curl --location --request GET \"$BASE_URL/v3/banks\" \\\r\n  --header \"X-XFERS-USER-API-KEY: $CUSTOMER_API_KEY\""
      tags:
      - Bank Account
      summary: Get Bank and Abbreviation Mapping
      description: This will provide you with a list of banks we support. Usually used for Add Bank Account API
      security:
      - X-XFERS-USER-API-KEY: []
      parameters:
      - $ref: '#/components/securitySchemes/X-XFERS-USER-API-KEY'
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
              - name: Bank Central Asia
                abbreviation: BCA
                img_src: https://d2ukkkjyjaezp4.cloudfront.net/assets/bank-logo-bca-181848fa16527e50b887013cf0cb7b90ae7b89181cf2a49b563d2a9c99cf42ee.png
                bank_code: '014'
                swift_code: CENAIDJA
              - name: Bank Mandiri
                abbreviation: MANDIRI
                img_src: https://d2ukkkjyjaezp4.cloudfront.net/assets/bank-logo-mandiri-3c9030412a3deb3c41589344a9a7bf74a52ef8dd278834d400b917f35e1b3bf9.png
                bank_code: 008
                swift_code: BMRIIDJA
              - name: Bank Negara Indonesia
                abbreviation: BNI
                img_src: https://d2ukkkjyjaezp4.cloudfront.net/assets/bank-logo-bni-dbb77bff33ad2bcd69f45600e4e53593a8bde8ce947175e055163b9f908898fb.png
                bank_code: 009
                swift_code: BNINIDJA
              - name: Bank Permata
                abbreviation: PERMATA
                img_src: https://d2ukkkjyjaezp4.cloudfront.net/assets/bank-logo-permata-32f25d774c784800bf92310ab010491d5f18af9fecef716ce1c61bb2ce12070d.png
                bank_code: '013'
                swift_code: BBBAIDJA
              - name: Bank Rakyat Indonesia
                abbreviation: BRI
                img_src: https://d2ukkkjyjaezp4.cloudfront.net/assets/bank-logo-bri-84ffad390f2ab1033df3254d47ef61b6ed47f73495503eb8d0a8eb82c36966a4.png
                bank_code: '002'
                swift_code: BRINIDJA359
              - name: CIMB Niaga Bank
                abbreviation: CIMB_NIAGA
                img_src: null
                bank_code: '022'
                swift_code: BNIAIDJA
              - name: Bank Danamon
                abbreviation: DANAMON
                img_src: null
                bank_code: '011'
                swift_code: BDINIDJA
              - name: Bank Panin
                abbreviation: PANIN
                img_src: null
                bank_code: 019
                swift_code: PINBIDJA
              - name: Bank Maybank
                abbreviation: BII
                img_src: null
                bank_code: '016'
                swift_code: MBBEIDJA
              - name: Anglomas International Bank
                abbreviation: ANGLOMAS
                img_src: null
                bank_code: '531'
                swift_code: LOMAIDJ1
              - name: Bangkok Bank
                abbreviation: BANGKOK
                img_src: null
                bank_code: '040'
                swift_code: BKKBIDJA
              - name: Bank Agris
                abbreviation: AGRIS
                img_src: null
                bank_code: '945'
                swift_code: FINBIDJA
              - name: Sinarmas
                abbreviation: SINARMAS
                img_src: null
                bank_code: '153'
                swift_code: SBJKIDJA
              - name: Bank Agroniaga
                abbreviation: AGRONIAGA
                img_src: null
                bank_code: '494'
                swift_code: AGTBIDJA
              - name: Bank Andara
                abbreviation: ANDARA
                img_src: null
                bank_code: '466'
                swift_code: RIPAIDJ1
              - name: Bank Antar Daerah
                abbreviation: ANTAR_DAERAH
                img_src: null
                bank_code: 088
                swift_code: ANTDIDJD
              - name: Bank ANZ Indonesia
                abbreviation: ANZ
                img_src: null
                bank_code: '061'
                swift_code: ANZBIDJX
              - name: Bank Artha Graha International
                abbreviation: ARTHA
                img_src: null
                bank_code: '037'
                swift_code: ARTGIDJA
              - name: Bank Artos Indonesia
                abbreviation: ARTOS
                img_src: null
                bank_code: '542'
                swift_code: ATOSIDJ1
              - name: Bank Bisnis Internasional
                abbreviation: BISNIS
                img_src: null
                bank_code: '459'
                swift_code: BUSTIDJ1
              - name: Bank BJB
                abbreviation: BJB
                img_src: null
                bank_code: '110'
                swift_code: PDJBIDJA
              - name: Bank BNP Paribas
                abbreviation: BNP
                img_src: null
                bank_code: '057'
                swift_code: BNPAIDJA
              - name: Bank Bukopin
                abbreviation: BUKOPIN
                img_src: null
                bank_code: '441'
                swift_code: BBUKIDJA
              - name: Bank Bumi Arta
                abbreviation: BUMI_ARTA
                img_src: null
                bank_code: '076'
                swift_code: BBAIIDJA
              - name: Bank Capital Indonesia
                abbreviation: CAPITAL
                img_src: null
                bank_code: '054'
                swift_code: CRLYIDJA
              - name: Bank Central Asia (BCA) Syariah
                abbreviation: BCA_SYR
                img_src: null
                bank_code: '536'
                swift_code: UIBAIDJ1
              - name: Bank Chinatrust Indonesia
                abbreviation: CHINATRUST
                img_src: null
                bank_code: '949'
                swift_code: CTCBIDJA
              - name: Bank CIMB Niaga UUS
                abbreviation: CIMB_UUS
                img_src: null
                bank_code: '022'
                swift_code: SYNAIDJ1
              - name: Bank Commonwealth
                abbreviation: COMMONWEALTH
                img_src: null
                bank_code: '950'
                swift_code: BICNIDJA
              - name: Bank Danamon UUS
                abbreviation: DANAMON_UUS
                img_src: null
                bank_code: '771'
                swift_code: SYBDIDJ1
              - name: Bank DBS Indonesia
                abbreviation: DBS
                img_src: null
                bank_code: '046'
                swift_code: DBSBIDJA
              - name: Bank Dinar Indonesia
                abbreviation: DINAR_INDONESIA
                img_src: null
                bank_code: '526'
                swift_code: LMANIDJ1
              - name: Bank DKI
                abbreviation: DKI
                img_src: null
                bank_code: '111'
                swift_code: BDKIIDJ1
              - name: Bank DKI UUS
                abbreviation: DKI_UUS
                img_src: null
                bank_code: '778'
                swift_code: SYDKIDJ1
              - name: Bank Ekonomi Raharja
                abbreviation: EKONOMI_RAHARJA
                img_src: null
                bank_code: 087
                swift_code: EKONIDJA
              - name: Bank Fama International
                abbreviation: FAMA
                img_src: null
                bank_code: '562'
                swift_code: FAMAIDJ1
              - name: Bank Ganesha
                abbreviation: GANESHA
                img_src: null
                bank_code: '161'
                swift_code: GNESIDJA
              - name: Bank Hana
                abbreviation: HANA
                img_src: null
                bank_code: '484'
                swift_code: HNBNIDJA
              - name: Bank Harda Internasional
                abbreviation: HARDA_INTERNASIONAL
                img_src: null
                bank_code: '567'
                swift_code: HRDAIDJ1
              - name: Bank Himpunan Saudara 1906
                abbreviation: HIMPUNAN_SAUDARA
                img_src: null
                bank_code: '212'
                swift_code: BSDRIDJA
              - name: Bank ICBC Indonesia
                abbreviation: ICBC
                img_src: null
                bank_code: '164'
                swift_code: ICBKIDJA
              - name: Bank Ina Perdana
                abbreviation: INA_PERDANA
                img_src: null
                bank_code: '513'
                swift_code: INPBIDJ1
              - name: Bank Index Selindo
                abbreviation: INDEX_SELINDO
                img_src: null
                bank_code: '555'
                swift_code: BIDXIDJA
              - name: Bank Jasa Jakarta
                abbreviation: JASA_JAKARTA
                img_src: null
                bank_code: '472'
                swift_code: JSABIDJ1
              - name: Bank Kesejahteraan Ekonomi
                abbreviation: KESEJAHTERAAN_EKONOMI
                img_src: null
                bank_code: '535'
                swift_code: KSEBIDJ1
              - name: Bank Maspion Indonesia
                abbreviation: MASPION
                img_src: null
                bank_code: '157'
                swift_code: MASDIDJ1
              - name: Bank Mayapada International
                abbreviation: MAYAPADA
                img_src: null
                bank_code: 097
                swift_code: MAYAIDJA
              - name: Bank Maybank Syariah Indonesia
                abbreviation: MAYBANK_SYR
                img_src: null
                bank_code: '947'
                swift_code: MBBEIDJA
              - name: Bank Mayora
                abbreviation: MAYORA
                img_src: null
                bank_code: '553'
                swift_code: YORAIDJ1
              - name: Bank Mega
                abbreviation: MEGA
                img_src: null
                bank_code: '426'
                swift_code: MEGAIDJA
              - name: Bank Mestika Dharma
                abbreviation: MESTIKA_DHARMA
                img_src: null
                bank_code: '151'
                swift_code: MEDHIDS1
              - name: Bank Metro Express
                abbreviation: METRO_EXPRESS
                img_src: null
                bank_code: '152'
                swift_code: MEEKIDJ1
              - name: Bank Mizuho Indonesia
                abbreviation: MIZUHO
                img_src: null
                bank_code: 048
                swift_code: MHCCIDJA
              - name: Bank MNC Internasional
                abbreviation: MNC_INTERNASIONAL
                img_src: null
                bank_code: '485'
                swift_code: BUMIIDJA
              - name: Bank Muamalat Indonesia
                abbreviation: MUAMALAT
                img_src: null
                bank_code: '147'
                swift_code: MUABIDJA
              - name: Bank Multi Arta Sentosa
                abbreviation: MULTI_ARTA_SENTOSA
                img_src: null
                bank_code: '548'
                swift_code: MASBIDJ1
              - name: Bank Mutiara
                abbreviation: MUTIARA
                img_src: null
                bank_code: 095
                swift_code: CICTIDJA
              - name: Bank Nationalnobu
                abbreviation: NATIONALNOBU
                img_src: null
                bank_code: '503'
                swift_code: LFIBIDJ1
              - name: Bank Nusantara Parahyangan
                abbreviation: NUSANTARA_PARAHYANGAN
                img_src: null
                bank_code: '145'
                swift_code: NUPAIDJ6
              - name: Bank OCBC NISP
                abbreviation: OCBC
                img_src: null
                bank_code: 028
                swift_code: NISPIDJA
              - name: Bank OCBC NISP UUS
                abbreviation: OCBC_UUS
                img_src: null
                bank_code: 028
                swift_code: SYONIDJ1
              - name: Bank of America Merill-Lynch
                abbreviation: BAML
                img_src: null
                bank_code: '033'
                swift_code: BOFAID2X
              - name: Bank of China (BOC)
                abbreviation: BOC
                img_src: null
                bank_code: 069
                swift_code: BKCHIDJA
              - name: Bank of India Indonesia
                abbreviation: INDIA
                img_src: null
                bank_code: '146'
                swift_code: BKIDIDJA
              - name: Bank of Tokyo Mitsubishi UFJ
                abbreviation: TOKYO
                img_src: null
                bank_code: '042'
                swift_code: BOTKJPJT
              - name: Bank Panin Syariah
                abbreviation: PANIN_SYR
                img_src: null
                bank_code: '517'
                swift_code: ARFAIDJ1
              - name: Bank Permata UUS
                abbreviation: PERMATA_UUS
                img_src: null
                bank_code: '784'
                swift_code: SYBBIDJ1
              - name: Bank Pundi Indonesia
                abbreviation: PUNDI_INDONESIA
                img_src: null
                bank_code: '558'
                swift_code: EKSTIDJ1
              - name: Bank QNB Kesawan
                abbreviation: QNB_KESAWAN
                img_src: null
                bank_code: '167'
                swift_code: AWANIDJA
              - name: Bank Rabobank International Indonesia
                abbreviation: RABOBANK
                img_src: null
                bank_code: 089
                swift_code: RABOIDJA
              - name: Bank Resona Perdania
                abbreviation: RESONA
                img_src: null
                bank_code: '047'
                swift_code: BPIAIDJA
              - name: Bank Royal Indonesia
                abbreviation: ROYAL
                img_src: null
                bank_code: '501'
                swift_code: ROYBIDJ1
              - name: Bank Sahabat Purba Danarta
                abbreviation: SAHABAT_PURBA_DANARTA
                img_src: null
                bank_code: '547'
                swift_code: PUBAIDJ1
              - name: Bank Sahabat Sampoerna
                abbreviation: SAHABAT_SAMPOERNA
                img_src: null
                bank_code: '523'
                swift_code: BDIPIDJ1
              - name: Bank SBI Indonesia
                abbreviation: SBI_INDONESIA
                img_src: null
                bank_code: '498'
                swift_code: IDMOIDJ1
              - name: Bank Sinar Harapan Bali
                abbreviation: SINAR_HARAPAN_BALI
                img_src: null
                bank_code: '564'
                swift_code: SIHBIDJ1
              - name: Bank Sumitomo Mitsui Indonesia
                abbreviation: MITSUI
                img_src: null
                bank_code: '045'
                swift_code: SUNIIDJA
              - name: Bank Syariah BRI
                abbreviation: BRI_SYR
                img_src: null
                bank_code: '422'
                swift_code: DJARIDJ1
              - name: Bank Syariah Bukopin
                abbreviation: BUKOPIN_SYR
                img_src: null
                bank_code: '774'
                swift_code: SDOBIDJ1
              - name: Bank Syariah Mandiri
                abbreviation: MANDIRI_SYR
                img_src: null
                bank_code: '451'
                swift_code: BSMDIDJA
              - name: Bank Syariah Mega
                abbreviation: MEGA_SYR
                img_src: null
                bank_code: '506'
                swift_code: BUTGIDJ1
              - name: Bank Tabungan Negara (BTN)
                abbreviation: BTN
                img_src: null
                bank_code: '200'
                swift_code: BTANIDJA
              - name: Bank Tabungan Negara (BTN) UUS
                abbreviation: BTN_UUS
                img_src: null
                bank_code: '200'
                swift_code: SYBTIDJ1
              - name: Bank Tabungan Pensiunan Nasional
                abbreviation: TABUNGAN_PENSIUNAN_NASIONAL
                img_src: null
                bank_code: '213'
                swift_code: TAPEIDJ1
              - name: Bank Tabungan Pensiunan Nasional UUS
                abbreviation: TABUNGAN_PENSIUNAN_NASIONAL_UUS
                img_src: null
                bank_code: '213'
                swift_code: SYTPIDJ1
              - name: Bank UOB Indonesia
                abbreviation: UOB
                img_src: null
                bank_code: '023'
                swift_code: BBIJIDJA
              - name: Bank Victoria Internasional
                abbreviation: VICTORIA_INTERNASIONAL
                img_src: null
                bank_code: '566'
                swift_code: VICTIDJ1
              - name: Bank Victoria Syariah
                abbreviation: VICTORIA_SYR
                img_src: null
                bank_code: '405'
                swift_code: SWAGIDJ1
              - name: Bank Windu Kentjana Int
                abbreviation: WINDU
                img_src: null
                bank_code: '036'
                swift_code: MCORIDJA
              - name: Bank Woori Indonesia
                abbreviation: WOORI
                img_src: null
                bank_code: 068
                swift_code: HVBKIDJA
              - name: Bank Yudha Bhakti
                abbreviation: YUDHA_BHAKTI
                img_src: null
                bank_code: '490'
                swift_code: YUDBIDJ1
              - name: BPD Aceh
                abbreviation: ACEH
                img_src: null
                bank_code: '116'
                swift_code: PDACIDJ1
              - name: BPD Aceh UUS
                abbreviation: ACEH_UUS
                img_src: null
                bank_code: '116'
                swift_code: SYACIDJ1
              - name: BPD Bali
                abbreviation: BALI
                img_src: null
                bank_code: '129'
                swift_code: ABALIDBS
              - name: BPD Bengkulu
                abbreviation: BENGKULU
                img_src: null
                bank_code: '133'
                swift_code: PDBKIDJ1
              - name: Bank Pembangunan Daerah (BPD DIY)
                abbreviation: BPD_DIY
                img_src: null
                bank_code: '112'
                swift_code: PDYKIDJ1
              - name: Bank Pembangunan Daerah (BPD DIY) Syariah
                abbreviation: BPD_DIY_SYR
                img_src: null
                bank_code: '112'
                swift_code: SYYKIDJ1
              - name: BPD Jambi
                abbreviation: JAMBI
                img_src: null
                bank_code: '115'
                swift_code: PDJMIDJ1
              - name: BPD Jambi UUS
                abbreviation: JAMBI_UUS
                img_src: null
                bank_code: '115'
                swift_code: SYJMIDJ1
              - name: BPD Jawa Tengah
                abbreviation: JAWA_TENGAH
                img_src: null
                bank_code: '113'
                swift_code: PDJGIDJ1
              - name: BPD Jawa Tengah UUS
                abbreviation: JAWA_TENGAH_UUS
                img_src: null
                bank_code: '113'
                swift_code: SYJGIDJ1
              - name: BPD Jawa Timur
                abbreviation: JAWA_TIMUR
                img_src: null
                bank_code: '114'
                swift_code: PDJTIDJ1
              - name: BPD Jawa Timur UUS
                abbreviation: JAWA_TIMUR_UUS
                img_src: null
                bank_code: '114'
                swift_code: SYJTIDJ1
              - name: BPD Kalimantan Barat
                abbreviation: KALIMANTAN_BARAT
                img_src: null
                bank_code: '123'
                swift_code: PDKBIDJ1
              - name: BPD Kalimantan Barat UUS
                abbreviation: KALIMANTAN_BARAT_UUS
                img_src: null
                bank_code: '123'
                swift_code: SYKBIDJ1
              - name: BPD Kalimantan Selatan
                abbreviation: KALIMANTAN_SELATAN
                img_src: null
                bank_code: '122'
                swift_code: PDKSIDJ1
              - name: BPD Kalimantan Selatan UUS
                abbreviation: KALIMANTAN_SELATAN_UUS
                img_src: null
                bank_code: '122'
                swift_code: SYKSIDJ1
              - name: BPD Kalimantan Tengah
                abbreviation: KALIMANTAN_TENGAH
                img_src: null
                bank_code: '125'
                swift_code: PDKGIDJ1
              - name: BPD Kalimantan Timur
                abbreviation: KALIMANTAN_TIMUR
                img_src: null
                bank_code: '124'
                swift_code: PDKTIDJ1
              - name: BPD Kalimantan Timur UUS
                abbreviation: KALIMANTAN_TIMUR_UUS
                img_src: null
                bank_code: '124'
                swift_code: SYKTIDJ1
              - name: BPD Lampung
                abbreviation: LAMPUNG
                img_src: null
                bank_code: '121'
                swift_code: PDLPIDJ1
              - name: BPD Maluku
                abbreviation: MALUKU
                img_src: null
                bank_code: '131'
                swift_code: PDMLIDJ1
              - name: BPD Nusa Tenggara Barat
                abbreviation: NUSA_TENGGARA_BARAT
                img_src: null
                bank_code: '128'
                swift_code: PDNBIDJ1
              - name: BPD Nusa Tenggara Barat UUS
                abbreviation: NUSA_TENGGARA_BARAT_UUS
                img_src: null
                bank_code: '128'
                swift_code: SYNBIDJ1
              - name: BPD Nusa Tenggara Timur
                abbreviation: NUSA_TENGGARA_TIMUR
                img_src: null
                bank_code: '130'
                swift_code: PDNTIDJ1
              - name: BPD Papua
                abbreviation: PAPUA
                img_src: null
                bank_code: '132'
                swift_code: PDIJIDJ1
              - name: BPD Riau Dan Kepri
                abbreviation: RIAU_DAN_KEPRI
                img_src: null
                bank_code: '119'
                swift_code: PDRIIDJA
              - name: BPD Riau Dan Kepri UUS
                abbreviation: RIAU_DAN_KEPRI_UUS
                img_src: null
                bank_code: '119'
                swift_code: SYRIIDJ1
              - name: BPD Sulawesi Tengah
                abbreviation: SULAWESI
                img_src: null
                bank_code: '134'
                swift_code: PDWGIDJ1
              - name: BPD Sulawesi Tenggara
                abbreviation: SULAWESI_TENGGARA
                img_src: null
                bank_code: '135'
                swift_code: PDWRIDJ1
              - name: BPD Sulselbar
                abbreviation: SULSELBAR
                img_src: null
                bank_code: '126'
                swift_code: PDWSIDJ1
              - name: BPD Sulselbar UUS
                abbreviation: SULSELBAR_UUS
                img_src: null
                bank_code: '126'
                swift_code: SYWSIDJ1
              - name: BPD Sulut
                abbreviation: SULUT
                img_src: null
                bank_code: '127'
                swift_code: PDWUIDJ1
              - name: BPD Sumatera Barat
                abbreviation: SUMATERA_BARAT
                img_src: null
                bank_code: '118'
                swift_code: PDSBIDJ1
              - name: BPD Sumatera Barat UUS
                abbreviation: SUMATERA_BARAT_UUS
                img_src: null
                bank_code: '118'
                swift_code: SYSBIDJ1
              - name: BPD Sumsel Dan Babel
                abbreviation: SUMSEL_DAN_BABEL
                img_src: null
                bank_code: '120'
                swift_code: BSSPIDSP
              - name: BPD Sumsel Dan Babel UUS
                abbreviation: SUMSEL_DAN_BABEL_UUS
                img_src: null
                bank_code: '120'
                swift_code: SYSSIDJ1
              - name: BPD Sumut
                abbreviation: SUMUT
                img_src: null
                bank_code: '117'
                swift_code: PDSUIDJ1
              - name: BPD Sumut UUS
                abbreviation: SUMUT_UUS
                img_src: null
                bank_code: '117'
                swift_code: SYSUIDJ1
              - name: Centratama Nasional Bank
                abbreviation: CENTRATAMA
                img_src: null
                bank_code: '559'
                swift_code: CNBAIDJ1
              - name: Citibank
                abbreviation: CITIBANK
                img_src: null
                bank_code: '031'
                swift_code: CITIIDJX
              - name: Deutsche Bank
                abbreviation: DEUTSCHE
                img_src: null
                bank_code: '067'
                swift_code: DEUTIDJA
              - name: Hongkong and Shanghai Bank Corporation (HSBC)
                abbreviation: HSBC
                img_src: null
                bank_code: '041'
                swift_code: HSBCIDJA
              - name: Hongkong and Shanghai Bank Corporation (HSBC) UUS
                abbreviation: HSBC_UUS
                img_src: null
                bank_code: '041'
                swift_code: SYHSIDJ1
              - name: JP Morgan Chase Bank
                abbreviation: JPMORGAN
                img_src: null
                bank_code: '032'
                swift_code: CHASIDJX
              - name: Prima Master Bank
                abbreviation: PRIMA_MASTER
                img_src: null
                bank_code: '520'
                swift_code: PMASIDJ1
              - name: Royal Bank of Scotland (RBS)
                abbreviation: PRIMA_MASTER
                img_src: null
                bank_code: '052'
                swift_code: ABNAIDJA
              - name: Standard Charted Bank
                abbreviation: STANDARD_CHARTERED
                img_src: null
                bank_code: '050'
                swift_code: SCBLIDJX
              - name: Bank Mitra Niaga
                abbreviation: MITRA_NIAGA
                img_src: null
                bank_code: '491'
                swift_code: MGABIDJ1
              - name: Bank Ekspor Indonesia
                abbreviation: EKSPOR_INDONESIA
                img_src: null
                bank_code: '003'
                swift_code: BEXIIDJA
              - name: Bank Arta Niaga Kencana
                abbreviation: ARTA_NIAGA_KENCANA
                img_src: null
                bank_code: '020'
                swift_code: ARNKIDJ1
              - name: Bank BJB Syariah
                abbreviation: BJB_SYR
                img_src: null
                bank_code: '425'
                swift_code: PDJBIDJA
              - name: Bank BNI Syariah
                abbreviation: BNI_SYR
                img_src: null
                bank_code: 009
                swift_code: SYNIIDJ1
        4XX:
          $ref: '#/components/responses/v3Error:4XX'
components:
  examples:
    XFE403:
      summary: XFE403 - ...
      value:
        error: string
        error_code: XFE403
        error_handling: '...'
    XFE111:
      summary: XFE1 - Duplicate credentials
      value:
        error: string
        error_code: XFE111
        error_handling: Particulars already exist. Please make sure you entered the correct parameters.
    XFE3:
      summary: XFE3 - Internal Error
      value:
        error: string
        error_code: XFE3
        error_handling: Unexpected error. Try again later or contact customer support at https://bit.ly/XfersSupport.
    XFE312:
      summary: XFE312 - Conditions not met to close account
      value:
        error: string
        error_code: XFE312
        error_handling: Invalid request to close account. Follow instruction in the response.
    XFE1:
      summary: XFE1 - Server busy
      value:
        error: string
        error_code: XFE1
        error_handling: Follow instructions in the response.
    XFE311:
      summary: XFE311 - Cannot be different wallet type
      value:
        error: string
        error_code: XFE311
        error_handling: Follow instruction in response or contact customer support at https://bit.ly/XfersSupport.
    XFE301:
      summary: XFE301 - Account locked
      value:
        error: string
        error_code: XFE301
        error_handling: Request not available. Please contact customer support at https://bit.ly/XfersSupport.
    XFE108:
      summary: XFE108 - More user information required
      value:
        error: string
        error_code: XFE108
        error_handling: Follow instructions in the response.
    XFE107:
      summary: XFE107 - Only enter one auth_code
      value:
        error: string
        error_code: XFE107
        error_handling: Do not enter both OTP or Google Auth OTP. Only need to enter one.
    XFE402:
      summary: XFE402 - Cannot use placeholder account
      value:
        error: string
        error_code: XFE402
        error_handling: Follow instructions in response.
    XFE502:
      summary: XFE502 - Unexpected BANK API error
      value:
        error: string
        error_code: XFE502
        error_handling: Try again later or contact customer support at https://bit.ly/XfersSupport.
    XFE106:
      summary: XFE106 - No auth_code provided
      value:
        error: string
        error_code: XFE106
        error_handling: Enter either phone OTP or Google Auth OTP
    XFE407:
      summary: XFE407 - Conditions to charge card not met
      value:
        error: string
        error_code: XFE407
        error_handling: Invalid request for this transaction. Make sure you entered the correct txn_id.
    XFE409:
      summary: XFE409 - Order id exist
      value:
        error: string
        error_code: XFE409
        error_handling: Please enter another order_id.
    XFE105:
      summary: XFE105 - Captcha error
      value:
        error: string
        error_code: XFE1
        error_handling: Follow instructions in the response.
    XFE404:
      summary: XFE404 - Forex not supported
      value:
        error: string
        error_code: XFE404
        error_handling: Make sure you call the correct API or contact customer support at https://bit.ly/XfersSupport.
    XFE102:
      summary: XFE102 - Entered value is less than minimum
      value:
        error: string
        error_code: XFE102
        error_handling: Make sure you entered the correct number.
    XFE109:
      summary: XFE109 - Invalid credentials
      value:
        error: string
        error_code: XFE109
        error_handling: Make sure you entered the correct credentials.
    XFE104:
      summary: XFE104 - Media provided too large
      value:
        error: string
        error_code: XFE104
        error_handling: Media too big. Follow the guidelines in the response.
    XFE15:
      summary: XFE15 - Required parameter empty
      value:
        error: string
        error_code: XFE15
        error_handling: Make sure you entered the correct required parameter.
    XFE14:
      summary: XFE14 - API only allowed for fully verified user
      value:
        error: string
        error_code: XFE14
        error_handling: Please submit KYC data to get your account fully verified.
    XFE2:
      summary: XFE2 - Access denied
      value:
        error: string
        error_code: XFE2
        error_handling: Make sure you call the correct API or contact customer support at https://bit.ly/XfersSupport.
    XFE506:
      summary: XFE506 - Bank account already taken
      value:
        error: string
        error_code: XFE506
        error_handling: Please use another bank account.
    XFE309:
      summary: XFE309 - Cannot use same account
      value:
        error: string
        error_code: XFE309
        error_handling: Follow instructions in the response.
    XFE13:
      summary: XFE13 - Record not found
      value:
        error: string
        error_code: XFE13
        error_handling: Please check that you provided the correct API Key and the correct parameters.
    XFE8:
      summary: XFE8 - Cannot retrieve media
      value:
        error: string
        error_code: XFE8
        error_handling: Cannot retrieve media. Please enter a new URL or try again later.
    XFE7:
      summary: XFE7 - Database error
      value:
        error: string
        error_code: XFE7
        error_handling: Follow instructions in the response.
    XFE408:
      summary: XFE408 - Invalid charge request
      value:
        error: string
        error_code: XFE408
        error_handling: Invalid request. Please follow instructions in response or contact customer support at https://bit.ly/XfersSupport.
    XFE302:
      summary: XFE302 - Account deleted
      value:
        error: string
        error_code: XFE302
        error_handling: Request not available. Please contact customer support at https://bit.ly/XfersSupport.
    XFE201:
      summary: XFE201 - Not yet a merchant
      value:
        error: string
        error_code: XFE201
        error_handling: Please verify your merchant or business account.
    XFE103:
      summary: XFE103 - ...
      value:
        error: string
        error_code: XFE103
        error_handling: Follow instructions in the response.
    XFE406:
      summary: XFE406 - Cannot refund prepaid transaction
      value:
        error: string
        error_code: XFE406
        error_handling: Please choose another transaction to refund.
    XFE401:
      summary: XFE401 - Cannot refund charge
      value:
        error: string
        error_code: XFE401
        error_handling: Invalid request. Please call another API or Contact customer support at https://bit.ly/XfersSupport.
    XFE503:
      summary: XFE503 - Failed name check
      value:
        error: string
        error_code: XFE503
        error_handling: Bank account name and name provided have to be similar.
    XFE410:
      summary: XFE410 - Invalid application fee
      value:
        error: string
        error_code: XFE410
        error_handling: Invalid request. Please make changes to the parameters as stated in the response.
    XFE304:
      summary: XFE304- Account closed
      value:
        error: string
        error_code: XFE304
        error_handling: Request not available. Please contact customer support at https://bit.ly/XfersSupport.
    XFE110:
      summary: XFE110 - Cannot sign up twice
      value:
        error: string
        error_code: XFE110
        error_handling: Please sign in instead
    XFE504:
      summary: XFE504 - Maximum number of bank account
      value:
        error: string
        error_code: XFE504
        error_handling: Delete existing bank accounts.
    XFE16:
      summary: XFE16 - Invalid request
      value:
        error: string
        error_code: XFE16
        error_handling: API request not supported. Make sure you entered the correct API key or contact customer support at https://bit.ly/XfersSupport.
    XFE310:
      summary: XFE310 - Cannot use same account
      value:
        error: string
        error_code: XFE310
        error_handling: Follow instructions in the response.
    XFE9:
      summary: XFE9 - ....
      value:
        error: string
        error_code: XFE9
        error_handling: '...'
    XFE601:
      summary: XFE601 - Conditions to withdraw not met. Can be solved by changing amount
      value:
        error: string
        error_code: XFE601
        error_handling: Your withdrawal does not meet the conditions required. Please follow the instructions in the response.
    XFE10:
      summary: XFE10 - Invalid environment
      value:
        error: string
        error_code: XFE10
        error_handling: Request not supported for this environment.
    XFE4:
      summary: XFE4 - Authentication field empty
      value:
        error: string
        error_code: XFE4
        error_handling: Follow instructions in the response.
    XFE307:
      summary: XFE307 - ...
      value:
        error: string
        error_code: XFE307
        error_handling: '...'
    XFE303:
      summary: XFE303 - Account terminated
      value:
        error: string
        error_code: XFE303
        error_handling: Request not available. Please contact customer support at https://bit.ly/XfersSupport.
    XFE101:
      summary: XFE101 - Not local number
      value:
        error: string
        error_code: XFE101
        error_handling: Follow instructions in the response.
    XFE405:
      summary: XFE405 - Charge cannot be refunded
      value:
        error: string
        error_code: XFE405
        error_handling: Only completed contract can be refunded.
    XFE505:
      summary: XFE505 - Bank abbrev provided invalid
      value:
        error: string
        error_code: XFE505
        error_handling: Use GET {{base-api-url}}api/v3/banks to get the correct bank abbrev.
    XFE6:
      summary: XFE6 - Invalid signature
      value:
        error: string
        error_code: XFE6
        error_handling: Follow instructions in the response.
    XFE5:
      summary: XFE5 - Api key is invalid
      value:
        error: string
        error_code: XFE5
        error_handling: Make sure you entered the correct API key or contact customer support at https://bit.ly/XfersSupport
    XFE603:
      summary: XFE603 - Not allowed to carry out request
      value:
        error: string
        error_code: XFE603
        error_handling: Invalid request. Please call another API or contact customer support at https://bit.ly/XfersSupport.
    XFE12:
      summary: XFE12 - Invalid parameter
      value:
        error: string
        error_code: XFE12
        error_handling: Make sure you entered the correct parameters.
    XFE306:
      summary: XFE306 - ...
      value:
        error: string
        error_code: XFE306
        error_handling: '...'
    XFE602:
      summary: XFE602 - Server busy
      value:
        error: string
        error_code: XFE602
        error_handling: Your withdrawal exceeds the limit for the time period. Please change the amount or verify your account.
    XFE11:
      summary: XFE11 - Timeout
      value:
        error: string
        error_code: XFE11
        error_handling: Please try again later.
    XFE308:
      summary: XFE308 - ...
      value:
        error: string
        error_code: XFE308
        error_handling: '...'
    XFE501:
      summary: XFE501 - Expected Bank API error
      value:
        error: string
        error_code: XFE501
        error_handling: Try again later or contact customer support at https://bit.ly/XfersSupport.
    XFE112:
      summary: XFE112 - Repeat request
      value:
        error: string
        error_code: XFE112
        error_handling: API request has already been made. Please follow the instructions in the response or call aother API.
    XFE305:
      summary: XFE305 - ....
      value:
        error: string
        error_code: XFE305
        error_handling: '...'
  schemas:
    error_response:
      type: object
      properties:
        error:
          description: Error Message
          type: string
        error_code:
          description: Xfers' error code XFEXXX
          type: string
        error_handling:
          description: Instruction on how to handle error. Refer to Error Codes tag for more information.
          type: string
  securitySchemes:
    X-XFERS-USER-API-KEY:
      type: apiKey
      name: X-XFERS-USER-API-KEY
      in: header
      description: You can retrieve this by using [get_token API](../sg/api/cutting-edge#operation/getToken)
  responses:
    v3Error:4XX:
      description: List of possible errors
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error_response'
          examples:
            XFE1:
              $ref: '#/components/examples/XFE1'
            XFE2:
              $ref: '#/components/examples/XFE2'
            XFE3:
              $ref: '#/components/examples/XFE3'
            XFE4:
              $ref: '#/components/examples/XFE4'
            XFE5:
              $ref: '#/components/examples/XFE5'
            XFE6:
              $ref: '#/components/examples/XFE6'
            XFE7:
              $ref: '#/components/examples/XFE7'
            XFE8:
              $ref: '#/components/examples/XFE8'
            XFE9:
              $ref: '#/components/examples/XFE9'
            XFE10:
              $ref: '#/components/examples/XFE10'
            XFE11:
              $ref: '#/components/examples/XFE11'
            XFE12:
              $ref: '#/components/examples/XFE12'
            XFE13:
              $ref: '#/components/examples/XFE13'
            XFE14:
              $ref: '#/components/examples/XFE14'
            XFE15:
              $ref: '#/components/examples/XFE15'
            XFE16:
              $ref: '#/components/examples/XFE16'
            XFE101:
              $ref: '#/components/examples/XFE101'
            XFE102:
              $ref: '#/components/examples/XFE102'
            XFE103:
              $ref: '#/components/examples/XFE103'
            XFE104:
              $ref: '#/components/examples/XFE104'
            XFE105:
              $ref: '#/components/examples/XFE105'
            XFE106:
              $ref: '#/components/examples/XFE106'
            XFE107:
              $ref: '#/components/examples/XFE107'
            XFE108:
              $ref: '#/components/examples/XFE108'
            XFE109:
              $ref: '#/components/examples/XFE109'
            XFE110:
              $ref: '#/components/examples/XFE110'
            XFE111:
              $ref: '#/components/examples/XFE111'
            XFE112:
              $ref: '#/components/examples/XFE112'
            XFE201:
              $ref: '#/components/examples/XFE201'
            XFE301:
              $ref: '#/components/examples/XFE301'
            XFE302:
              $ref: '#/components/examples/XFE302'
            XFE303:
              $ref: '#/components/examples/XFE303'
            XFE304:
              $ref: '#/components/examples/XFE304'
            XFE305:
              $ref: '#/components/examples/XFE305'
            XFE306:
              $ref: '#/components/examples/XFE306'
            XFE307:
              $ref: '#/components/examples/XFE307'
            XFE308:
              $ref: '#/components/examples/XFE308'
            XFE309:
              $ref: '#/components/examples/XFE309'
            XFE310:
              $ref: '#/components/examples/XFE310'
            XFE311:
              $ref: '#/components/examples/XFE311'
            XFE312:
              $ref: '#/components/examples/XFE312'
            XFE401:
              $ref: '#/components/examples/XFE401'
            XFE402:
              $ref: '#/components/examples/XFE402'
            XFE403:
              $ref: '#/components/examples/XFE403'
            XFE404:
              $ref: '#/components/examples/XFE404'
            XFE405:
              $ref: '#/components/examples/XFE405'
            XFE406:
              $ref: '#/components/examples/XFE406'
            XFE407:
              $ref: '#/components/examples/XFE407'
            XFE408:
              $ref: '#/components/examples/XFE408'
            XFE409:
              $ref: '#/components/examples/XFE409'
            XFE410:
              $ref: '#/components/examples/XFE410'
            XFE501:
              $ref: '#/components/examples/XFE501'
            XFE502:
              $ref: '#/components/examples/XFE502'
            XFE503:
              $ref: '#/components/examples/XFE503'
            XFE504:
              $ref: '#/components/examples/XFE504'
            XFE505:
              $ref: '#/components/examples/XFE505'
            XFE506:
              $ref: '#/components/examples/XFE506'
            XFE601:
              $ref: '#/components/examples/XFE601'
            XFE602:
              $ref: '#/components/examples/XFE602'
            XFE603:
              $ref: '#/components/examples/XFE603'
externalDocs:
  description: Find out more about Xfers
  url: https://id.xfers.com
x-tagGroups:
- name: User Management
  tags:
  - Registration
  - User Account
  - Bank Account
  - E-signature
- name: Payments
  tags:
  - Charge
  - Payout
  - Withdraw
  - Intents
- name: Loans
  tags:
  - Loans
  - Disbursements
  - Repayments
- name: Appendix
  tags:
  - Testing
  - Error Response
  - Pagination
  - Callback Configuration
  - Try it out with Postman
